resolver: lts-24.11
compiler: ghc-9.10.2
allow-newer: true
packages:
- '.' 
extra-deps:
- dequeue-0.1.12
- git: https://github.com/ucsd-progsys/elsa
  commit: f872270763a8b343075d92953cdddcefe323fca7
